# Generated by Django 2.1.3 on 2018-11-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almoxarifado',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
