# Generated by Django 2.1.3 on 2018-12-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0003_auto_20181201_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almoxarifado',
            name='descrição',
            field=models.TextField(),
        ),
    ]
