# Generated by Django 2.1.3 on 2018-12-03 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0004_auto_20181201_1647'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Almoxarifado',
            new_name='Item',
        ),
    ]
