# Generated by Django 2.1.3 on 2018-12-03 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0008_auto_20181203_0850'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
