# Generated by Django 2.1.3 on 2018-12-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0011_delete_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_categoria', models.CharField(max_length=100)),
            ],
        ),
    ]
