# Generated by Django 2.1.3 on 2018-12-03 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0013_auto_20181203_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='almoxarifado.Categoria'),
            preserve_default=False,
        ),
    ]
