# Generated by Django 2.1.3 on 2018-12-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0015_auto_20181203_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
